# Generated by Django 5.0.6 on 2024-05-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('username', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=512)),
                ('name', models.CharField(max_length=512)),
                ('surname', models.CharField(max_length=512)),
                ('nationality', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='CoachTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField()),
                ('coach_id', models.CharField(max_length=20)),
                ('contract_start', models.DateField()),
                ('contract_finish', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseManager',
            fields=[
                ('username', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Jury',
            fields=[
                ('username', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=512)),
                ('name', models.CharField(max_length=512)),
                ('surname', models.CharField(max_length=512)),
                ('nationality', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='MatchSession',
            fields=[
                ('session_id', models.IntegerField(primary_key=True, serialize=False)),
                ('team_id', models.IntegerField()),
                ('stadium_id', models.IntegerField()),
                ('time_slot', models.IntegerField()),
                ('date', models.CharField(max_length=512)),
                ('assigned_jury_username', models.CharField(max_length=512)),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('username', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=512)),
                ('name', models.CharField(max_length=512)),
                ('surname', models.CharField(max_length=512)),
                ('date_of_birth', models.CharField(max_length=512)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerPositions',
            fields=[
                ('player_positions_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=512)),
                ('position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerTeams',
            fields=[
                ('player_teams_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=512)),
                ('team', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('position_id', models.IntegerField(primary_key=True, serialize=False)),
                ('position_name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='SessionSquads',
            fields=[
                ('squad_id', models.IntegerField(primary_key=True, serialize=False)),
                ('session_id', models.IntegerField()),
                ('played_player_username', models.CharField(max_length=512)),
                ('position_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('stadium_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stadium_country', models.CharField(max_length=512)),
                ('stadium_name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=512)),
                ('coach_username', models.CharField(max_length=512)),
                ('contract_start', models.CharField(max_length=512)),
                ('contract_finish', models.CharField(max_length=512)),
                ('channel_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TVChannel',
            fields=[
                ('channel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=512)),
            ],
        ),
    ]
